### ISSUE TITLE
css样式引用貌似有问题

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbsMD#1]

**Comment by atjiu** [comment]
兼容模式我给关了，assets里的页面，css，js都没用到

**Comment by TakWolf** [comment]
普通的css是有问题的，你看一下夜间模式

**Comment by TakWolf** [comment]
找到原因了，class="markdown-text" 这个需要调整一下

**Comment by atjiu** [comment]
修好了，cnode渲染的html外貌有一个div包着，class是markdown-text，我写的接口渲染后的html没有那个样式导致的，谢谢你提醒

**Comment by atjiu** [comment]
顺便问下，`String umengAppKey = System.getenv('CNODEMD_UMENG_APP_KEY')`
这个变量是在哪地方定义的？CNODEMD_UMENG_APP_KEY

**Comment by atjiu** [comment]
@TakWolf 我在个人用户下的.bash_profile里定了一下，echo也可以输出变量值，但编译就是不通过，一直都是`Error:Cause: null value in entry: UMENG_APPKEY=null`请教

**Comment by TakWolf** [comment]
环境变量定义CNODEMD_UMENG_APP_KEY
或者在local.properties中定义umeng.appkey都可以，后者优先级高一些

你检查一下这里，是不是你给写死为null了
https://github.com/tomoya92/pybbsMD/blob/master/app/build.gradle#L4

**Comment by TakWolf** [comment]
友盟如果不用的话，直接删除吧

**Comment by atjiu** [comment]
@TakWolf 好的，谢谢，我配置在.bash_profile里是对的对吧！
